### ISSUE TITLE
sqrt 

### ISSUE THREAD

**Issue by citron** [jlaragonvera/Geometric-Algebra#3]
Hello and thanks for this nice module.
How do I compute symbolic expressions of square roots of multivectors using CGAlgebra, please ?
![CGAlgebra_sqrt_problem](https://user-images.githubusercontent.com/161367/67557764-f9460400-f715-11e9-8916-81e7d2551aad.png)
In the above example, we see that the sqrt is not evaluated.

**Comment by jlaragonvera** [comment]
Sorry for taking so long to respond. The square root of a multivector is not defined in CGAlgebra. I you want to use the Mathematica function, you should capitalize as Sqrt[...].
